### ISSUE TITLE
Please support null safety

### ISSUE THREAD

**Issue by ZheruiL** [xiaozhizhong/merge_images#4]
Great helper for merging images, however it does not support null safety and I have to copy your code to my project to make it run. Please update a little bit for this package

**Comment by xiaozhizhong** [comment]
This package has supported null-safety 13 months ago. Have you found bugs of null-safety compatibility?

**Comment by ZheruiL** [comment]
<img width="587" alt="截屏2022-04-06 上午9 55 51" src="https://user-images.githubusercontent.com/27128660/161880318-66dbc212-4852-4fdc-b455-eca904e83edc.png">

<img width="637" alt="截屏2022-04-06 上午9 56 36" src="https://user-images.githubusercontent.com/27128660/161880338-f0a5033b-c5af-45ff-be92-dc7a8329dda6.png">

No, because I didn't find the version 2.0 before 😂  
Maybe change the tag from Prerelase to Stable

**Comment by xiaozhizhong** [comment]
Pub automatically classifies version with null-safety tag to Pre-Release😂.
Will close this issue if you have no other questions.

**Comment by ZheruiL** [comment]
Yeah, no more questions here, thank you
